config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('miniforum.urls')),
]

miniforum/urls.py
from django.urls import path

from . import views

app_name = 'miniforum'
urlpatterns = [
    path('', views.IndexView.as_view()),
    path('threads/', views.ThreadIndexView.as_view(), name='thread_index'),
    path('threads/create/', views.ThreadCreateView.as_view(), name='thread_create'),
    path('threads/<int:pk>/', views.ThreadDetailView.as_view(), name='thread_detail'),
    path('threads/<int:pk>/posts', views.PostIndexView.as_view(), name='post_index'),
    path('threads/<int:pk>/posts/create', views.PostCreateView.as_view(), name='post_create'),
    path('threads/<int:pk>/report', views.ReportCreateView.as_view(), name='report_create'),
    path('threads/<int:pk>/report/done', views.ReportDoneView.as_view(), name='report_done'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register')
]

miniforum/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

class Thread(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(default=None, null=True, blank=True)
    
class Post(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    ip_address = models.CharField(max_length=100)
    deleted_at = models.DateTimeField(default=None, null=True, blank=True)
    content = models.CharField(max_length=1000)
    
    def format_created_at(self):
        localtime = timezone.localtime(self.created_at)
        date = localtime.strftime("%Y/%m/%d")
        dayOfWeek = ["月", "火", "水", "木", "金", "土", "日"][localtime.weekday()]
        time = localtime.strftime("%H:%M")
        return date + " (" + dayOfWeek + ") " + time

class Report(models.Model):
    thread = models.ForeignKey(Thread, null=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    ip_address = models.CharField(max_length=100)
    dealt_at = models.DateTimeField(default=None, null=True, blank=True)
    content = models.CharField(max_length=1000)

    def synopsis(self):
        return self.content[0:20]

miniforum/forms.py
from django import forms
from django.contrib.auth.models import User

class ThreadForm(forms.Form):
    template_name = 'miniforum/form.html'
    title = forms.CharField(max_length=100, label="スレッド名", widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(max_length=1000, label="投稿内容", widget=forms.Textarea(attrs={'rows':6, 'class': 'form-control'}))
    
class PostForm(forms.Form):
    template_name = 'miniforum/form.html'
    content = forms.CharField(max_length=1000, label="投稿内容", widget=forms.Textarea(attrs={'rows':6, 'class': 'form-control'}))

class ReportForm(forms.Form):
    template_name = 'miniforum/form.html'
    content = forms.CharField(max_length=1000, label="通報内容", widget=forms.Textarea(attrs={'rows':6, 'class': 'form-control'}))

class LoginForm(forms.Form):
    template_name = 'miniforum/form.html'
    username = forms.CharField(required=True, max_length=150, label="ユーザー名", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(required=True, label="パスワード", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class RegisterForm(forms.Form):
    template_name = 'miniforum/form.html'
    username = forms.CharField(required=True, max_length=150, label="ユーザー名", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(required=True, label="パスワード", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password_confirm = forms.CharField(required=True, label="パスワード（再入力）", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def is_valid(self):
        valid = super().is_valid()
        if self.data['password'] != self.data['password_confirm']:
            self.add_error('password_confirm', "再入力パスワードが一致しませんでした。")
            return False
        else:
            return valid

miniforum/views.py
from django.contrib.auth import authenticate, login, views as auth_views
from django.contrib.auth.models import User
from django.db import transaction
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic

from .forms import LoginForm, PostForm, RegisterForm, ReportForm, ThreadForm
from .models import Post, Report, Thread

def get_ip_address(request):
    if 'HTTP_X_FORWARDED_FOR' in request.META:
        return request.META['HTTP_X_FORWARDED_FOR']
    else:
        return request.META['REMOTE_ADDR']

def get_thread_or_404(id):
    return get_object_or_404(Thread, pk=id, deleted_at=None)
    
class IndexView(generic.base.RedirectView):
    permanent = True
    query_string = False
    pattern_name = 'miniforum:thread_index'

class ThreadIndexView(generic.ListView):
    model = Thread
    paginate_by = 20
    template_name = 'miniforum/thread_index.html'
    ordering = '-updated_at'

    def get_queryset(self):
        return Thread.objects.filter(deleted_at=None).order_by('-updated_at')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_obj = context['page_obj']
        context['paginator_range'] = paginator.get_elided_page_range(page_obj.number, on_ends=1)
        return context
        
class ThreadCreateView(generic.FormView):
    template_name = 'miniforum/thread_create.html'
    form_class = ThreadForm
    
    def form_valid(self, form):
        with transaction.atomic():
            thread = Thread(title=form.cleaned_data['title'])
            thread.save()
            post = Post(thread=thread, content=form.cleaned_data['content'], ip_address=get_ip_address(self.request))
            if self.request.user.is_authenticated:
                post.user = self.request.user
            post.save()
        return HttpResponseRedirect(reverse('miniforum:thread_detail', args=(thread.pk,)))

class ThreadDetailView(generic.base.RedirectView):
    permanent = True
    query_string = False
    pattern_name = 'miniforum:post_index'

class PostIndexView(generic.ListView):
    paginate_by = 100
    template_name = 'miniforum/post_index.html'

    def get_queryset(self):
        thread = get_thread_or_404(self.kwargs['pk'])
        return thread.post_set.order_by('created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['thread'] = get_thread_or_404(self.kwargs['pk'])
        paginator = context['paginator']
        page_obj = context['page_obj']
        context['paginator_range'] = paginator.get_elided_page_range(page_obj.number, on_ends=1)
        return context
    
class PostCreateView(generic.FormView):
    template_name = 'miniforum/post_create.html'
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['thread'] = get_thread_or_404(self.kwargs['pk'])
        return context
        
    def form_valid(self, form):
        with transaction.atomic():
            thread = get_thread_or_404(self.kwargs['pk'])
            post = Post(thread=thread, content=form.cleaned_data['content'], ip_address=get_ip_address(self.request))
            if self.request.user.is_authenticated:
                post.user = self.request.user
            thread.save() # updated_atを更新
            post.save()
        return HttpResponseRedirect(reverse('miniforum:thread_detail', args=(thread.pk,)))

class ReportCreateView(generic.FormView):
    template_name = 'miniforum/report_create.html'
    form_class = ReportForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['thread'] = get_thread_or_404(self.kwargs['pk'])
        return context
        
    def form_valid(self, form):
        with transaction.atomic():
            thread = get_thread_or_404(self.kwargs['pk'])
            report = Report(thread=thread, content=form.cleaned_data['content'], ip_address=get_ip_address(self.request))
            if self.request.user.is_authenticated:
                report.user = self.request.user
            report.save()
        return HttpResponseRedirect(reverse('miniforum:report_done', args=(thread.pk,)))
    
class ReportDoneView(generic.TemplateView):
    template_name = 'miniforum/report_done.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['thread'] = get_thread_or_404(self.kwargs['pk'])
        return context

class LoginView(generic.FormView):
    template_name = 'miniforum/login.html'
    form_class = LoginForm

    def form_valid(self, form):
        user = authenticate(self.request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        if user is not None:
            login(self.request, user)
            return HttpResponseRedirect(reverse('miniforum:thread_index'))
        else:
            form.add_error(None, "ユーザー名かパスワードが間違っています。")
            return super().form_invalid(form)

class LogoutView(auth_views.LogoutView):
    next_page = reverse_lazy('miniforum:thread_index')

class RegisterView(generic.FormView):
    template_name = 'miniforum/register.html'
    form_class = RegisterForm

    def form_valid(self, form):
        with transaction.atomic():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                form.add_error(None, "既に存在しているユーザー名です。")
                return super().form_invalid(form)
            user = User.objects.create_user(form.cleaned_data['username'], None, form.cleaned_data['password'])
        login(self.request, user)
        return HttpResponseRedirect(reverse('miniforum:thread_index'))

miniforum/templates/miniforum/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>{% block 'title' %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container-fluid">
	  <span class="navbar-brand">MiniForum</span>
	  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-links">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbar-links">
	    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
	      <li class="nav-item">
		<a class="nav-link" href="{% url 'miniforum:thread_index' %}">スレッド一覧</a>
	      </li>
	      <li class="nav-item">
		<a class="nav-link" href="{% url 'miniforum:thread_create' %}">スレッド作成</a>
	      </li>
	    </ul>
	    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
	      {% if user.is_authenticated %}
	      <li class="nav-item">
		<form action="{% url 'miniforum:logout' %}" method="post" onsubmit="return confirm(&quot;ログアウトしますか？&quot;);">
		  {% csrf_token %}
		  <input type="submit" value="ログアウト" class="btn btn-outline-danger">
		</form>
	      </li>
	      {% else %}
	      <li class="nav-item">
		<a class="nav-link" href="{% url 'miniforum:login' %}">ログイン</a>
	      </li>
	      <li class="nav-item">
		<a class="nav-link" href="{% url 'miniforum:register' %}">登録</a>
	      </li>
	      {% endif %}
	    </ul>
	  </div>
	</div>
      </nav>
    </header>
    <main class="container-fluid">
      <div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
	  {% block 'content' %}{% endblock %}
	</div>
	<div class="col-md-3"></div>
      </div>
    </main>
  </body>
</html>

miniforum/templates/miniforum/form.html
{{ form.non_field_errors }}
{% for field in form %}
<div class="my-2">
  {{ field.errors }}
  <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
    {{ field }}
  {% if field.help_text %}
  <p>{{ field.help_text|safe }}</p>
  {% endif %}
</div>
{% endfor %}

miniforum/templates/miniforum/login.html
{% extends 'miniforum/base.html' %}

{% block 'title' %} ログイン - MiniForum {% endblock %}

{% block 'content' %}
<h1 class="my-2">ログイン</h1>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="ログイン" class="btn btn-primary">
</form>
{% endblock %}

miniforum/templates/miniforum/pagination.html
{% if page_obj.has_other_pages %}
<nav class="my-2 d-flex justify-content-center">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">&lt;</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">&lt;</a></li>
    {% endif %}
    {% for i in paginator_range %}
    {% if i == Paginator.ELLIPSIS %}
    <li class="page-item disabled"><span class="page-link">…</span></li>
    {% else %}
    <li class="page-item{% if i == page_obj.number %} active{% endif %}"><a class="page-link" href="{{ request.path }}?page={{ i }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">&gt;</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">&gt;</a></li>
    {% endif %}
</nav>
{% endif %}

miniforum/templates/miniforum/post_create.html
{% extends 'miniforum/base.html' %}

{% block 'title' %} 投稿 - MiniForum {% endblock %}

{% block 'content' %}
<h1 class="my-2">{{ thread.title }} - 投稿</h1>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <div class="my-2">
    <input type="submit" value="投稿" class="btn btn-primary">
  </div>
</form>
<div class="my-2">
  <a href="{% url 'miniforum:thread_detail' thread.pk %}">スレッドに戻る</a>
</div>
{% endblock %}

miniforum/templates/miniforum/post_index.html
{% extends 'miniforum/base.html' %}

{% block 'title' %} {{ thread.title }} - MiniForum {% endblock %}

{% block 'content' %}
<h1 class="my-2">{{ thread.title }}</h1>
{% load serial_number %}
<div class="mx-1">
  {% for post in post_list %}
  <div class="my-3">
    {% if post.deleted_at != None %}
    <div class="text-muted small">
      {% serial_number paginator.per_page page_obj.number forloop.counter %}.
      この投稿は削除されました。
    </div>
    {% else %}
    <div class="mb-1">{% serial_number paginator.per_page page_obj.number forloop.counter %}.
      {% if post.user == None %}
      <small class="text-secondary">匿名</small>
      {% else %}
      {{ post.user.username }}
      {% endif %}
      {{ post.format_created_at }}
    </div>
    <div class="mx-1">{{ post.content|linebreaksbr }}</div>
    {% endif %}
  </div>
  {% if not forloop.last %}
  <div class="mx-2 border border-top-3" style="border-style: dashed !important;"></div>
  {% endif %}
  {% endfor %}
</div>
{% include 'miniforum/pagination.html' %}
<div class="my-2">
  <a href="{% url 'miniforum:post_create' thread.pk %}">投稿</a>
  <a href="{% url 'miniforum:report_create' thread.pk %}">通報</a>
</div>
{% endblock %}

miniforum/templates/miniforum/register.html
{% extends 'miniforum/base.html' %}

{% block 'title' %} ユーザー登録 - MiniForum {% endblock %}

{% block 'content' %}
<h1>ユーザー登録</h1>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <div class="my-2">
    <input type="submit" value="登録" class="btn btn-primary">
  </div>
</form>
{% endblock %}

miniforum/templates/miniforum/report_create.html
{% extends 'miniforum/base.html' %}

{% block 'title' %} 通報 - MiniForum {% endblock %}

{% block 'content' %}
<h1 class="my-2">{{ thread.title }} - 通報</h1>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <div class="my-2">
    <input type="submit" value="通報" class="btn btn-primary">
  </div>
</form>
<div class="my-2">
  <a href="{% url 'miniforum:thread_detail' thread.pk %}">スレッドに戻る</a>
</div>
{% endblock %}

miniforum/templates/miniforum/report_done.html
{% extends 'miniforum/base.html' %}

{% block 'title' %} 通報 - MiniForum {% endblock %}

{% block 'content' %}
<h1 class="my-2">{{ thread.title }}</h1>
<p class="my-2">
  通報を受け付けました。
</p>
<div class="my-2">
  <a href="{% url 'miniforum:post_index' thread.pk %}">スレッドに戻る</a>
</div>
{% endblock %}

miniforum/templates/miniforum/thread_create.html
{% extends 'miniforum/base.html' %}

{% block 'title' %} スレッド作成 - MiniForum {% endblock %}

{% block 'content' %}
<h1 class="my-2">スレッド作成</h1>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <div class="my-2">
    <input type="submit" value="作成" class="btn btn-primary">
  </div>
</form>
{% endblock %}

miniforum/templates/miniforum/thread_detail.html
{% extends 'miniforum/base.html' %}

{% block 'title' %} {{ thread.title }} - MiniForum {% endblock %}

{% block 'content' %}
<h1>{{ thread.title }}</h1>
{% for post in thread.post_set.all %}
<div>
  <div>{{ forloop.counter }}.
    {% if post.user == None %}
    匿名
    {% else %}
    {% endif %}
    {{ post.format_created_at }}
  </div>
  <div>{{ post.content|linebreaksbr }}</div>
</div>
{% endfor %}
<div>
  <a href="{% url 'miniforum:post_create' thread.pk %}">書き込む</a>
</div>
<div>
  <a href="{% url 'miniforum:thread_index' %}">スレッド一覧</a>
</div>
{% endblock %}

miniforum/templates/miniforum/thread_index.html
{% extends 'miniforum/base.html' %}

{% block 'title' %} MiniForum {% endblock %}

{% block 'content' %}
<h1 class="my-2">スレッド一覧</h1>
<ul class="list-group list-group-flush my-2">
  {% for thread in thread_list %}
  <li class="list-group-item">
    <a href="{% url 'miniforum:thread_detail' thread.pk %}">{{ thread.title }}</a>
  </li>
  {% endfor %}
</ul>
{% include 'miniforum/pagination.html' %}
{% endblock %}